# Generated by Django 2.2.6 on 2019-11-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_auto_20191102_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sujet',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
