# Generated by Django 2.2.6 on 2019-11-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membre',
            field=models.BooleanField(default='False'),
        ),
    ]
