# Generated by Django 2.2.6 on 2019-11-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profileimage.png', upload_to='profile/'),
        ),
    ]
