# Generated by Django 2.2.6 on 2019-11-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptesApp', '0002_auto_20191101_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='imageprofile',
            field=models.ImageField(default='profileimage.png', upload_to='profile'),
        ),
    ]
