# Generated by Django 2.2.6 on 2019-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptesApp', '0003_auto_20191101_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageprofile',
            field=models.ImageField(default='profileimage.png', null=True, upload_to='profile'),
        ),
    ]
