# Generated by Django 2.2.6 on 2019-11-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptesApp', '0004_auto_20191101_2243'),
        ('comptesApp', '0002_profile_membre'),
    ]

    operations = [
    ]
