# Generated by Django 2.2.6 on 2019-11-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptesApp', '0005_merge_20191102_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='membre',
        ),
    ]
