# Generated by Django 2.2.6 on 2019-11-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptesApp', '0006_remove_profile_membre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
