# Generated by Django 2.2.6 on 2019-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='maps',
        ),
        migrations.AddField(
            model_name='info',
            name='latitude',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='longitude',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
    ]
