# Generated by Django 2.2.6 on 2019-11-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor_infos_user',
            options={'verbose_name': 'Visitor_Infos_user', 'verbose_name_plural': 'Visitor_Infos_users'},
        ),
    ]
