# Generated by Django 2.2.6 on 2019-11-01 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptesApp', '0001_initial'),
        ('statistiqueApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_de_lecture', models.CharField(max_length=255, null=True)),
                ('titre', models.CharField(max_length=255)),
                ('titre_slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=255, null=True)),
                ('description', models.TextField()),
                ('contenu', tinymce.models.HTMLField(null=True, verbose_name='article_description')),
                ('photo', models.ImageField(upload_to='article')),
                ('nb_com', models.PositiveIntegerField()),
                ('nb_like', models.PositiveIntegerField()),
                ('nb_re_commentaitre', models.PositiveIntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('contenu', models.TextField(null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='blogApp.Article')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptesApp.Profile')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaire des postes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues_articles', to='blogApp.Article')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='statistiqueApp.Visitor_Infos_user')),
            ],
            options={
                'verbose_name': 'Vue',
                'verbose_name_plural': 'Vues',
            },
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('query', models.CharField(max_length=250)),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchs', to='statistiqueApp.Visitor_Infos_user')),
            ],
            options={
                'verbose_name': 'serarch',
                'verbose_name_plural': 'les recherches des utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('contenu', models.TextField(null=True)),
                ('commentaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='blogApp.Commentaire')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptesApp.Profile')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'reponse aux commentaires',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blogApp.Article')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_visiteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='categorie')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctegorieuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categorie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blogApp.Categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag_name',
            field=models.ManyToManyField(related_name='tag_article', to='blogApp.Tag'),
        ),
    ]
