# Generated by Django 2.2.6 on 2019-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nb_like',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='nb_re_commentaitre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
