# Generated by Django 2.2.6 on 2019-11-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20191101_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nb_com',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
