# Generated by Django 2.2.6 on 2019-11-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_reply_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nb_com',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='nb_like',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='nb_re_commentaitre',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
