# Generated by Django 2.2.6 on 2019-11-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20191101_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_user', to='comptesApp.Profile'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreply', to='comptesApp.Profile'),
        ),
    ]
